version: "3.7"

# Local development setup

volumes:
    pg_data:
        name: "postgres_data"
    redis-session-data:
        name: "redis-session-data"

networks:
    backend:
        driver: bridge

services:
    postgresql:
        image: postgres:12-alpine
        volumes:
            - pg_data:/var/lib/postgresql/data
            - ./config/postgres/passwd:/run/secrets/postgres-passwd             # secret file
        expose:
            - 5432
        ports:
            - 127.0.0.1:5432:5432
        networks:
            - backend
        environment:
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd               
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres

    flyway:
        build: ./flyway
        networks:
            - backend
        depends_on:
            - postgresql

    rabbitmq:
        image: rabbitmq:3.8-management
        networks:
            - backend
        expose:
            - 5672
        ports:
            - 127.0.0.1:5672:5672
            - 127.0.0.1:15672:15672
