version: "3.7"

# Local development setup

networks:
    backend:
        driver: bridge

services:
    postgres:
        build: ./postgres
        expose:
            - 5432
        ports:
            - 127.0.0.1:5432:5432
        networks:
            - backend
        volumes:
            - postgres-data:/var/lib/postgresql/data

    flyway:
        build: ./flyway
        networks:
            - backend
        depends_on:
            - postgres

    rabbitmq:
        build: ./rabbitmq
        hostname: rabbit-host
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - backend
        expose:
            - 5672
        ports:
            - 127.0.0.1:5672:5672
            - 127.0.0.1:15672:15672

volumes:
    postgres-data:
    rabbitmq-data:
