version: "3.7"

# Local development setup

networks:
    backend:
    pg-backend:
    rabbit-auth-net:
    redis-authorization-code-storage:
    redis-mobile-auth-server:

services:
    pgbouncer:
        image: docker.pkg.github.com/yunbaby-org/pgbouncer/pgbouncer:latest
        expose:
            - 5432
        ports: 
            - 127.0.0.1:5432:5432
        networks:
            - pg-backend
            - backend
        environment:
            - DATABASES_HOST=postgres
            - PGBOUNCER_AUTH_TYPE=md5
            - PGBOUNCER_AUTH_FILE=./userlist.txt
        depends_on:
            - postgres
            - flyway

    postgres:
        image: docker.pkg.github.com/yunbaby-org/postgres/postgres:latest
        expose:
            - 5432
        ports:
            - 127.0.0.1:5433:5432
        networks:
            - pg-backend
        volumes:
            - postgres-data:/var/lib/postgresql/data

    flyway:
        image: docker.pkg.github.com/yunbaby-org/flyway-migraiton/flyway-migraiton:latest
        networks:
            - backend
            - pg-backend
        restart: on-failure
        environment:
            - PGBOUNCER_ROLE_PASSWORD=RichGangsterRobbingTheB@nk666
        depends_on:
            - postgres
    rabbitmq:
        image: docker.pkg.github.com/yunbaby-org/rabbitmq/rabbitmq:latest
        hostname: rabbit-host
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - backend
            - rabbit-auth-net
        expose:
            - 5672
        ports:
            - 0.0.0.0:5672:5672
            - 0.0.0.0:15674:15674
            - 127.0.0.1:15672:15672

    pgadmin4:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_LISTEN_PORT=5050
            - PGADMIN_DEFAULT_EMAIL=someone@somewhere
            - PGADMIN_DEFAULT_PASSWORD=password
        ports:
            - 127.0.0.1:5050:5050
        networks:
            - backend

    rabbitmq-authn-http:
        image: docker.pkg.github.com/yunbaby-org/rabbitmq-auth-backend-http/rabbitmq-auth-server:latest
        expose:
            - 80
        ports:
            - 0.0.0.0:12300:80
        networks:
            - rabbit-auth-net
            - redis-authorization-code-storage
        environment:
            - REDIS_HOST=redis-authorization-code-storage
            - REDIS_PORT=6379
            - AUTH=AUTHN
        depends_on:
            - redis-authorization-code-storage

    rabbitmq-authz-http:
        image: docker.pkg.github.com/yunbaby-org/rabbitmq-auth-backend-http/rabbitmq-auth-server:latest
        expose:
            - 80
        networks:
            - rabbit-auth-net
            - redis-authorization-code-storage
        environment:
            - REDIS_HOST=redis-authorization-code-storage
            - REDIS_PORT=6379
            - AUTH=AUTHZ

    redis-authorization-code-storage:
        image: redis:6
        expose:
            - 6379
        networks:
            - redis-authorization-code-storage
            
    boundary-monitor:
        image: docker.pkg.github.com/yunbaby-org/boundary-monitor/boundary-monitor:0.1
        restart: always
        networks: 
            - backend
        environment: 
            - DB_HOST=pgbouncer
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASS=password
            - RABBITMQ_USER=guest
            - RABBITMQ_PASS=guest
            - RABBITMQ_PORT=5672
            - RABBITMQ_HOST=rabbitmq
            - SMS_USER=b10617046
            - SMS_PASS=p499uycb
        depends_on:
            - rabbitmq
            - postgres

    response-monitor:
        image: docker.pkg.github.com/yunbaby-org/response-monitor/response-monitor:0.3
        restart: always
        networks:
            - backend
        environment:
            - RABBITMQ_USER=guest
            - RABBITMQ_PASS=guest
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
            - PREFETCH_SIZE=10
            - DATABASE_HOST=pgbouncer
            - DATABASE_NAME=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASS=password

        depends_on:
            - rabbitmq
            - postgres

    nginx:
        build:
            context: ./nginx
        restart: always
        networks:
            - backend
        ports:
            - 0.0.0.0:80:80
        depends_on:
            - auth-server 
            - rest-server
            - mobile-authentication-server
            - rabbitmq-authn-http
#        command: [nginx-debug, '-g', 'daemon off;']

    auth-server:
        image: docker.pkg.github.com/yunbaby-org/server/auth_server:latest
        restart: always
        networks:
            - backend
        environment:
            - DBPORT=5432
            - DBDB=postgres
            - DBUSER=postgres
            - DBHOST=pgbouncer
            - DBPASSWORD=password
        depends_on:
            - postgres
            - pgbouncer

    rest-server:
        image: docker.pkg.github.com/yunbaby-org/server/rest_server:latest
        restart: always
        networks:
            - backend
        environment:
            - DBPORT=5432
            - DBDB=postgres
            - DBUSER=postgres
            - DBHOST=pgbouncer
            - DBPASSWORD=password
            - RABBITHOST=rabbitmq
            - RABBITPORT=5672
        depends_on:
            - postgres
            - pgbouncer


    mobile-authentication-server:
        image: docker.pkg.github.com/yunbaby-org/mobile-authentication-server/mobile-authentication-server:latest
        networks:
            - backend
            - redis-mobile-auth-server
        environment:
            - REDIS_HOST=mobile-authentication-server-redis
            - POSTGRES_HOST=pgbouncer
            - POSTGRES_PORT=5432
            - POSTGRES_DATABASE=postgres
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres
            - APP_HOST=0.0.0.0
            - APP_PORT=3000
        depends_on:
            - postgres
            - pgbouncer
            - mobile-authentication-server-redis


    mobile-authentication-server-redis:
        image: redis:6
        expose:
            - 6379
        networks:
            - redis-mobile-auth-server

volumes:
    postgres-data:
    rabbitmq-data:
