version: "3.7"

# Local development setup

networks:
    backend:
    rabbit-auth-net:
    redis-authorization-code-storage:

services:
    postgres:
        build: ./postgres
        expose:
            - 5432
        ports:
            - 127.0.0.1:5432:5432
        networks:
            - backend
        volumes:
            - postgres-data:/var/lib/postgresql/data

    flyway:
        build: ./flyway
        networks:
            - backend
        restart: on-failure
        depends_on:
            - postgres

    rabbitmq:
        build: ./rabbitmq
        hostname: rabbit-host
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        networks:
            - backend
            - rabbit-auth-net
        expose:
            - 5672
        ports:
            - 0.0.0.0:5672:5672
            - 127.0.0.1:15672:15672

    pgadmin4:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_LISTEN_PORT=5050
            - PGADMIN_DEFAULT_EMAIL=someone@somewhere
            - PGADMIN_DEFAULT_PASSWORD=password
        ports:
            - 127.0.0.1:5050:5050
        networks:
            - backend

    rabbitmq-authn-http:
        build: 
            context: ./rabbitmq-authentication-backend-http
        expose:
            - 80
        ports:
            - 0.0.0.0:12300:80
        networks:
            - rabbit-auth-net
            - redis-authorization-code-storage
        environment:
            - REDIS_HOST=redis-authorization-code-storage
            - REDIS_PORT=6379
            - AUTH=AUTHN

    rabbitmq-authz-http:
        build: 
            context: ./rabbitmq-authentication-backend-http
        expose:
            - 80
        networks:
            - rabbit-auth-net
            - redis-authorization-code-storage
        environment:
            - REDIS_HOST=redis-authorization-code-storage
            - REDIS_PORT=6379
            - AUTH=AUTHZ

    redis-authorization-code-storage:
        image: redis:6
        expose:
            - 6379
        networks:
            - redis-authorization-code-storage

    response-monitor:
        build:
            context: ./monitors/respones-monitor
        restart: always
        networks:
            - backend
        environment:
            - RABBITMQ_USER=guest
            - RABBITMQ_PASS=guest
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
            - PREFETCH_SIZE=10
        depends_on:
            - rabbitmq

volumes:
    postgres-data:
    rabbitmq-data:
